### PR TITLE
US126585 [CIPD] - CPD Hide Overall Progress / Progress by Subject Button on My CPD Page

### PR DESCRIPTION
**Pull request by Syeda-Azim**
https://rally1.rallydev.com/#/431372673576/iterationstatus?detail=%2Fuserstory%2F517481677852
image

### CODE REVIEW

**Review by lweber-d2l — APPROVED** [review]

**Review by imcdonald-d2l — CHANGES_REQUESTED** [review]
The `Overall Progress` and `Adjust Targets` header text needs more padding to be consistent with the distance between `Structured` header and the edge of the container.
image

**Comment by imcdonald-d2l** [comment]
Still some inconsistencies.
- Adjust targets text does not have the same margin.
- Bottom margin is too big now. You only need to add margin on the top and sides.

image

**Comment by Syeda-Azim** [comment]
> * Adjust targets text does not have the same margin.
 
 Haven't changes styling of Adjust targets text, it was always inconsistent with the toggle buttons. 
image

**Comment by imcdonald-d2l** [comment]
> > * Adjust targets text does not have the same margin.
> 
> Haven't changed styling of Adjust targets text, it was always inconsistent with the toggle buttons.
> image

Do you mind fixing it then? Should be pretty easy to fix.

**Comment by Syeda-Azim** [comment]
Done
image

**Review by imcdonald-d2l — APPROVED** [review]
Thanks for cleaning up the styles 🙂

**Pull request merged**
